const POST_TYPE = {
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",
  LOAD_POST_REQUEST: "LOAD_POST_REQUEST",
  LOAD_POST_SUCCESS: "LOAD_POST_SUCCESS",
  LOAD_POST_FAILURE: "LOAD_POST_FAILURE",
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  REMOVE_POST_REQUEST: "REMOVE_POST_REQUEST",
  REMOVE_POST_SUCCESS: "REMOVE_POST_SUCCESS",
  REMOVE_POST_FAILURE: "REMOVE_POST_FAILURE",
  REMOVE_COMMENT_REQUEST: "REMOVE_COMMENT_REQUEST",
  REMOVE_COMMENT_SUCCESS: "REMOVE_COMMENT_SUCCESS",
  REMOVE_COMMENT_FAILURE: "REMOVE_COMMENT_FAILURE",
};

export default POST_TYPE;
